global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: server
    scrape_interval: 15s
    static_configs:
      - targets: ['server:8000']
      
  - job_name: worker
    scrape_interval: 15s
    static_configs:
      - targets: ['worker:8001']
      
  - job_name: database
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres-exporter:9187']
